config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'shortlist', to: 'pages#shortlist', as: :shortlist
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :childcares, only: [:index, :show]

  resources :applications, only: [:new, :create, :show, :destroy, :index] do
    member do
      post 'toggle_favorite', to: "childcares#toggle_favorite"
    end
  end

  resources :users, only: [:show, :destroy]
  resources :children

end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :childcare
  belongs_to :child
  validates :start_date, presence: true
  enum status: {
    pending: 0,
    accepted: 1,
    declined: 2,
    wishlist: 3,
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :user
  has_many :applications, dependent: :destroy
  validates :first_name, :last_name, presence: true, length: { minimum: 2 }
  validates :dob, presence: true
end

app/models/childcare.rb
class Childcare < ApplicationRecord
  has_many :applications, dependent: :destroy
  has_many :users, through: :applications
  has_many :reviews, dependent: :destroy
  has_many :opening_hours, dependent: :destroy
  # validates :name, :url, presence: true
  # validates :address, presence: true, uniqueness: true
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  acts_as_favoritable
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/opening_hour.rb
class OpeningHour < ApplicationRecord
  belongs_to :childcare
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :childcare
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :children, dependent: :destroy
  has_many :applications, through: :children
  validates :address, :phone_number, presence: true
  validates :first_name, :last_name, presence: true, length: { minimum: 2 }
  validates :email, presence: true,uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  acts_as_favoritor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :address])
  end
end

def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController

  def index

  end

  def new
    @application = Application.new
  end

  def create

    @applications = []
    current_user.all_favorited.each do |childcare|
      @application = Application.new
      if list_params[:start_date].empty?
        start_date = Date.today
      else
        start_date = Date.parse(list_params[:start_date])
      end
        @application.start_date = start_date
        @application.childcare = childcare
        @application.child = current_user.children.first
        if @application.save
         @applications << @application
        else
          render :new
        end
    end
    ChildcareMailer.with(applications: @applications, user:current_user).new_childcare_email.deliver_now
    redirect_to root_path, flash: {notice: "Application was submitted Successfully. Check your email for details."}
  end

  def destroy
    @application = Application.find(params[:application_id])
    @application.destroy
    redirect_to childcare_applications_path(params[:childcare_id])
  end


  private

  def list_params
    params.require(:application).permit(:child_id, :start_date)
  end

end


# @booking.start_date = Date.parse(list_params[:date][0..9])

# start_date = Date.parse(list_params[:start_date])

app/controllers/childcares_controller.rb
class ChildcaresController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index

    if $childcares.nil? || params[:query].present?
      if params[:query].present?
        $childcares = []
        if  (params[:query] == "Melbourne" || params[:query] == "Richmond" || params[:query] == "3121")
          $childcares = Childcare.where("address ILIKE ?", "%VIC%")
        else
          $childcares = Childcare.where("address ILIKE ?", "%#{params[:query]}%")
        end
      else
        $childcares = Childcare.all
      end
    end

    @markers = $childcares.geocoded.map do |childcare|
      {
        lat: childcare.latitude,
        lng: childcare.longitude,
        info_window: render_to_string(partial: "info_window", locals: { childcare: childcare }),
        image_url: helpers.asset_url("map2.png")
      }
    end
  end

  def show
    @childcare = Childcare.find(params[:id])
    @markers =[
      {
        lat: @childcare.latitude,
        lng: @childcare.longitude,
        info_window: render_to_string(partial: "info_window", locals: { childcare: @childcare }),
        image_url: helpers.asset_url("map2.png")
      }
    ]
  end

  def toggle_favorite
    @childcare = Childcare.find(params[:id])
    current_user.favorited?(@childcare) ? current_user.unfavorite(@childcare) : current_user.favorite(@childcare)
  end

end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :find_child, only: [:show, :edit, :update, :destroy]
  def index
    @children = Child.all
  end

  def show
  end

  def new
    @child = Child.new
  end

  def create
    @child = Child.new(list_params)
    @child.user= current_user
    if @child.save
      redirect_to user_path(@child.user), notice: "Child added successfully"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(list_params)
      redirect_to user_path(@child.user), notice: "Child Eddited successfully"
    else
      render :edit
    end
  end

  def destroy
    @child.destroy
    redirect_to user_path(@child.user)
  end

  private

  def find_child
    @child = Child.find(params[:id])
  end

  def list_params
    params.require(:child).permit(:first_name, :last_name, :gender, :dob)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about]
  def home
  end

  def about


  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

  def destroy
    @childcare = Childcare.find(params[:id])
    current_user.unfavorite(@childcare)
    redirect_to shortlist_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/applications/new.html.erb
 <div class="application-form">
  <div class="form-body" style = "background-color: #FAEEE7;">
      <div class="row">
          <div class="form-holder" style="min-height: 0;">
              <div class="form-content">
                  <div class="form-items" style = "background-color: #325288; position: relative;">
                      <h3>Application Form</h3>
                      <p>The application will send your child name to all the daycares in your list</p>
                        <%= simple_form_for [@application]  do |f| %>
                          <%= f.error_notification %>
                          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
                          <% childrens_array =  current_user.children.map { |name| ["#{name.first_name}"] }%>
                          <%= f.text_field :start_date,
                          data: {
                            controller: "flatpickr",
                            flatpickr_date_format: ("d-m-Y"),
                            flatpickr_alt_format: t("date.formats.long"),
                            flatpickr_alt_input: true,
                          } ,placeholder: "When is the start date for you child?" %>
                          <%= f.select :child_id, childrens_array, label: false, prompt: "Pick from your Children", class:"date-form" %>
                          <%= f.button :submit, "Send Application", class:"button-primary mx-auto mt-7" %>
                        <% end %>
                      </form>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>

app/views/childcares/_info_window.html.erb
<div style="width: 200px">
  <div class="marker-img mx-2 my-1 text-center">
    <%= link_to childcare_path(childcare) do %>
    <figure><img img src='<%= childcare.photos.first.url if childcare.photos.attached? %>' alt="childcare" /></figure>
    <% end %>
  </div>

  <div class="mx-2 my-2">
    <h6><%= link_to childcare.name, childcare_path(childcare) %></h6>
    <p><%= childcare.address %></p>
  </div>
</div>

app/views/childcares/index.html.erb
<div class="d-flex justify-content-between " style="background-color: #FAEEE7;">
  <div>
    <div class="reminder d-flex justify-content-start align-items-center">
      <h4 class="mx-3">Add your child's profile and start application now !</h4>
      <% if user_signed_in? %>
        <%= link_to "GO", user_path(current_user), class: "button-primary" %>
      <% else %>
        <%= link_to "GO", new_user_session_path, class: "button-primary" %>
      <% end %>
    </div>
    <div class="childcares-small-cards">
      <% $childcares.each do |childcare| %>
        <%= render 'shared/childcare_small card', childcare: childcare %>
      <% end %>
    </div>
  </div>

  <div id="map"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/childcares/show.html.erb
<div class="py-4" style="background-color: #FAEEE7">
  <div class="container" >
    <i class="fas fa-solid fa-chevron-left icon-pink"></i>
    <%= link_to "Back to search results", childcares_path, class: "back-link"%>
  </div>
</div>


<%= render 'shared/show_photo_banner'%>

<div class="map-wrraper">
<div class="container d-flex justify-content-between">

  <div class="map-container w-75 mx-5">
    <div id="show-map"
        data-controller="mapbox"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
  <div class="opening-hours">
    <h2 style="padding-bottom: 20px; font-size: 24px"> <strong>Opening Hours</strong></h2>
    <ul>
      <% @childcare.opening_hours.each do |time| %>
      <li class="my-2" style="white-space: nowwrap; width:300px;"><%= time.time %></li>
      <% end  %>
    </ul>
  </div>
  </div>
</div>

<div style="background-color: #FAEEE7; padding-top:2px;">
  <div class="container mt-5" >
  <h1 class="review-title my-5" >Google Reviews for <%= @childcare.name %></h1>
    <% unless  @childcare.reviews.empty? %>
      <% @childcare.reviews.each do |review| %>
        <%= render 'shared/childcare_reviews', review: review %>
      <% end %>
    <% else %>
      <p class="me-5">NO GOOGLE REVIEWS</p>
    <% end %>
  </div>
</div>

app/views/children/edit.html.erb
  <h2>Edit Your Child's profile</h2>


 <%= link_to "Back", user_path(current_user) %>

app/views/children/new.html.erb
   <%# <%= f.input :first_name %>
    <%# <%= f.input :last_name %>
    <%# <%= f.input :gender %>
    <%# <%= f.input :dob %>
    <%# <%= f.submit %>

<%# ***********************************LINK TO SOURCE: https://codepen.io/samnorton/pen/oNYajYM %>

    <div class="form-body" style = "background-color: #FAEEE7; padding-top: 0px;">
      <div class="py-4" style="background-color: #FAEEE7">
        <div class="container" >
          <i class="fas fa-solid fa-chevron-left icon-pink"></i>
          <%= link_to "Back to profile", user_path(current_user), class: "back-link" %>
        </div>
      </div>
        <div class="row">
            <div class="form-holder" style="min-height: 0; background-color: #FAEEE7;">
                <div class="form-content", style= "padding-top: 20px;">
                    <div class="form-items" style = "background-color: #325288; position: relative;">
                        <h3>Register a child</h3>
                        <p>Fill in your child's details below:</p>
                          <%= simple_form_for @child do |f| %>
                            <%= f.label :first_name, "First name" %>
                            <%= f.input :first_name, required: true, label: false %>
                            <%= f.label :last_name, "Last name" %>
                            <%= f.input :last_name, required: true,label:false %>
                            <%= f.label :gender, "Gender" %>
                            <p style="margin-bottom: 0;"><%= f.select :gender, ['Male', 'Female'] %></p>
                            <%= f.label :dob, "Date Of Birth" %>
                            <%= f.text_field :dob,
                              data: {
                                controller: "flatpickr",
                                flatpickr_date_format: ("d-m-Y"),
                                flatpickr_alt_format: t("date.formats.long"),
                                flatpickr_alt_input: true,
                              }, class:"new-child-form" %>
                            <%= f.submit :Submit, class: "button-primary mt-8" %>
                          <% end %>
                         <div style = "position: absolute; top: 8px; right: 16px; width: 13rem;"><img src="https://res.cloudinary.com/dxu35uhgf/image/upload/v1655099317/development/babywithbackground_je2pyh.png" alt="Baby playing"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/children/show.html.erb
<h1><%= @child.first_name %> <%= @child.last_name %></h1>

 <%= link_to "Back", user_path(current_user) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Baybeme. You've got a lot to care about...let us take care of daycare!</title>

<%# Favicon below*********** %>
   <%= favicon_link_tag %>
<%# End of Favicon*********** %>

<%# Metatags below*********** %>
<title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">
<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />
<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:image:src" content="<%= meta_image %>">
<%# End of metatags*********** %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%# <link href="/dist/output.css" rel="stylesheet"> %>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@2.15.2/dist/full.css" rel="stylesheet" type="text/css" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_KEY'] %>&libraries=places&callback=initMap" async defer data-turbolinks-eval="false"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="content-wrapper">
      <%= yield %>
    </div>
    <%= render 'shared/flashes' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container about-container mb-5">
  <h1 style="font-weight: 700">About Us</h1>
  <p>
    Looking for a trustworthy and affordable childcare option? Look no further than our childcare search engine! We provide a comprehensive database of childcare providers in your area, complete with customer reviews and ratings.</p>
  <p>
    With our search engine, you can easily find a provider that meets your needs and budget. We also offer a variety of resources to help    you make the best decision for your family.</p>
  <p>
   <strong>Don't spend hours scouring the internet for the perfect childcare provider. Let our website do the work for you!</strong> </p>
  <p>
    We hope that our website will be a useful tool for you as you search for childcare. We know how important it is to find the right care for your child, and we are here to help. Thank you for using our website, and we wish you the best of luck in finding the perfect childcare for your family.</p>
</div>

app/views/pages/home.html.erb
<a name="top"></a>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.5)), url(<%= image_url('banner-test.jpg') %>);">
  <div class="container px-3">
    <h1>BaybeME</h1>
    <h3>You've got a lot to care about...let us take care of daycare</h3>
    <%= render 'shared/search' %>
  </div>
</div>
<hr>

<%= render 'shared/banner_right' %>

<%= render 'shared/reviews_banner' %>
<%= render 'shared/banner_left' %>

app/views/pages/shortlist.html.erb
<div class="py-4" style="background-color: #F4F4F4">
  <div class="container" >
    <i class="fas fa-solid fa-chevron-left icon-pink"></i>
    <%= link_to "Back to search results", childcares_path, class: "back-link"%>
  </div>
</div>
<div class="user-container mx-auto">
      <div class=" ">
        <div class="d-flex justify-content-between">
          <h1 class="title-panel-top">My Shortlist</h1>
          <% unless current_user.all_favorited.empty?%>
            <%= link_to "Send application to all", new_application_path, class: "button-primary" %>
          <% end %>
        </div>
        <hr class="my-4">
        <div class="py-1 mx-3">
          <% if current_user.all_favorited.empty?%>
            <p> You haven't shortlisted any childcare center</p>
          <% else %>
           <div class="row">
            <% current_user.all_favorited.each do |childcare| %>
              <% if childcare.photos.attached? %>
               <div class="col-md-4 my-3">
                <div class="card-shortlist bg-base-100 mx-3">
                  <%= link_to childcare_path(childcare) do %>
                  <figure><img img src='<%= childcare.photos.first.url %>' alt="childcare" /></figure>
                  <% end %>
                  <div class="small-card-body">
                    <h2 class="mb-3"><%= link_to childcare.name, childcare_path(childcare) %></h2>
                    <div class="d-flex justify-content-end align-items-center">
                      <%= link_to "Apply", new_application_path, class: "shortlist-apply" %>
                      <%= link_to user_path(childcare),
                          method: :delete,
                          data: { confirm: "Are you sure?" } do %>
                          <i class="fas fa-regular fa-trash icon-pink"></i>
                      <% end %>
                    </div>
                  </div>
                </div>
               </div>
              <% end %>
            <% end %>
           </div>
          <% end %>
        </div>
      </div>
    </div>

app/views/shared/_banner_left.html.erb
<div class="hero p-10 bg-base-200" style= "background-color: #FAEEE7; height: 480px">
  <div class="container px-3">
    <div class="hero-content px-0 flex-col lg:flex-row picture-transition">
      <img src="https://res.cloudinary.com/dxu35uhgf/image/upload/v1654667122/fnojhlqpgoe6x7wu0bbk.jpg" class="max-w-sm rounded-lg shadow-2xl" />
      <div class="ms-3">
        <h1 class="text-3xl font-bold">Send booking requests directly with Baybeme</h1>
        <p class="py-6">You can use Baybeme to contact all your chosen childcare in few clicks. You do not to search and contact each of them separately!</p>
        <a href="#top"><button class="button-primary" style="margin-left: 0;">Start searching now</button></a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_childcare_small card.html.erb
<% if childcare.photos.attached? %>
  <div class="card-mine w-96 bg-base-100">
    <%= link_to childcare_path(childcare) do %>
    <figure><img img src='<%= childcare.photos.first.url %>' alt="childcare" /></figure>
    <% end %>
    <div class="small-card-body">
      <h2 style="height:30px;"><%= link_to childcare.name, childcare_path(childcare) %></h2>
      <div class="d-flex justify-content-between">
        <div class="rating mt-3">
             <% (childcare.rating).to_i.times do %>
              <i class="rating-star fas fa-solid fa-star"></i>
             <% end %>
             <% if  (childcare.rating).to_i == 0 %>
              <i class="rating-star fas fa-solid fa-star"></i>
              <i class="rating-star fas fa-solid fa-star"></i>
              <i class="rating-star fas fa-solid fa-star"></i>
             <% end %>
          </div>
          <% if user_signed_in? %>
          <%= link_to current_user.favorited?(childcare) ? "Added" : "Add to shortlist", toggle_favorite_application_path(childcare),
                  remote: true,
                  method: :post,
                  class: current_user.favorited?(childcare) ? "button-outline" : "button-primary",
                  data: {
                    controller: 'shortlist-button',
                    action: 'click->shortlist-button#shortlist'
                  }
           %>
           <% else %>
            <%= link_to "Add to shortlist", new_user_session_path, class: "button-primary" %>
           <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1 notice-flash" role="alert">
    <button type="button" class="button-alert" data-bs-dismiss="alert" aria-label="Close">close</button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">CLOSE</button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm sticky-top navbar-light navbar-baby">
  <div class="container-fluid container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "baby-logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link tab-text" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link tab-text" %>
        </li>
        <li class="nav-item">
          <%= link_to "Childcares", childcares_path, class: "nav-link tab-text" %>
        </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "My Shortlist", shortlist_path, class: "nav-link tab-text" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item" style="padding-top: 10px">
          <%= link_to "Login", new_user_session_path, class: "main-button" %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<%# <div class="container h-100">
  <div class="d-flex h-100">
    <div class="searchbar">
        <input class="search_input" type="text" name="" placeholder="Enter your postcode">
        <a href="#" class="search_icon"><i class="fas fa-search"></i></a>
    </div>
  </div>
</div> %>
<div class="container h-100">
  <div class="d-flex h-100">
    <div class="searchbar">
      <%= form_tag childcares_path, method: :get do %>
        <%= text_field_tag :query,
              params[:query],
              class: "search_input",
              id: 'postcode-search',
              placeholder: "Enter your postcode or suburb"
        %>
        <%= button_tag type: 'submit', class: "search_icon" do %>
          <i class="fas fa-search"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_show_photo_banner.html.erb
<div class="py-4" style= "background-color: #FAEEE7">
  <div class="container d-flex justify-content-between align-items-start">
      <div class="photo-banner-content w-50 ps-0">
        <h1><%= @childcare.name %></h1>
        <p><i class="fas fa-regular fa-map-pin" style="color: #288568; margin-right: 8px"></i><%= @childcare.address %></p>
        <p><i class="fas fa-regular fa-envelope" style="color: #288568; margin-right: 8px"></i>
        <% unless @childcare.email.nil? %>
          <%= @childcare.email %></p>
        <% else %>
          <%= "#{@childcare.name.gsub(" ","")}@outlook.com" %></p>
        <% end %>
        <div class="cta">
          <% if user_signed_in? %>
          <%= link_to current_user.favorited?(@childcare) ? "Added" : "Add to shortlist", toggle_favorite_application_path(@childcare),
                  remote: true,
                  method: :post,
                  class: current_user.favorited?(@childcare) ? "button-outline" : "button-primary",
                  data: {
                    controller: 'shortlist-button',
                    action: 'click->shortlist-button#shortlist'
                  }
           %>
           <% else %>
            <%= link_to "Add to shortlist", new_user_session_path, class: "button-primary" %>
           <% end %>
        </div>

      </div>
      <div class="photo-banner-picture w-50">

        <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
              <div class="carousel-item active" data-bs-interval="10000">
                  <figure><img img src='<%= @childcare.photos.first.url %>' alt="childcare" style="width:100%;height: 380px;border-radius:15px;"/></figure>
              </div>
                <% unless @childcare.photos.drop(1).empty?%>
                  <% @childcare.photos.drop(1).each do |photo| %>
                    <div class="carousel-item" data-bs-interval="2000">
                        <figure><img img src='<%= photo.url %>' alt="childcare" style="width:100%;height: 380px;border-radius:15px;"/></figure>
                    </div>
                  <% end %>
                <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
  </div>
</div>